### ISSUE TITLE
Request "GET" ask to include header "Content-Type: application/json".

### ISSUE THREAD

**Issue by AgustinFlores11** [gurock/trcli#105]
### TestRail CLI Version

1.3.1

### CLI Environment

Windows 10 Enterprise, python 3.9

### TestRail Version

v5.7.1.4028

### TestRail Instance Type

NA

### Current behavior

I create a config file with my auth data, the host, and all data about the project-suite.
When i try to upload an xml report file to my Testrail test run, i get the follwing result:

> Checking project.
> Error detected while checking a project: 'Content-Type header missing (use Content-Type: application/json)'

### Desired behavior

After trying to upload an xml report file, the trcli should check the data about the project, suite and test cases online and update the resuls in the desired test run.

### More Details

Checking the code of api_client.py, i found headers where no added to requests of type "GET". Apparently this cause the error, i just add the headers to this request (as a test) and the upload was successful after that.

**Comment by AnastasiaOMatveeva** [comment]
How to solve this problem?

**Comment by smartuuu** [comment]
We have the same issue with Testrail v6.0.0. Modified api_client.py file and made a new build. It works now. Please fix it.
![image](https://user-images.githubusercontent.com/122566056/214586444-546485df-303c-4423-92bb-4421b0b8b628.png)

**Comment by Testinator-X** [comment]
@d-rede can you add this changes to the planned version 1.4.0?

**Comment by d-rede** [comment]
@AgustinFlores11 @AnastasiaOMatveeva @Testinator-X 

The headers are being added as of today's release `v1.4.2`. I hope this resolves the issue, but please open a new ticket if you still have problems.
