### ISSUE TITLE
Steps integration

### ISSUE THREAD

**Issue by simonepelosi** [gurock/trcli#116]
### What would you like the TestRail CLI to be able to do?

I'd like to able to upload steps on my test case.

### Interested in implementing it yourself?

Yes

**Comment by Testinator-X** [comment]
Duplicates https://github.com/gurock/trcli/issues/74

**Comment by d-rede** [comment]
As @Testinator-X mentioned, this is a duplicate and we will track it in https://github.com/gurock/trcli/issues/74. Closing the issue.
