### ISSUE TITLE
Field :type_id is not a valid case type.

### ISSUE THREAD

**Issue by awirl-foreflight** [gurock/trcli#126]
### TestRail CLI Version

1.4.2

### TestRail Version

7.5.6

### TestRail Instance Type

NA

### Current behavior

When I upload this file to the trcli, the result fails when trying to add these new test cases to my suite. I've been able to get other files to work but it doesn't work with this specific file for some reason. It's interesting because the type_id field is actually a integer which seems to fit the requirements for the cli tool but something is strange is happing at the /add_case API call.

[cypress.txt](https://github.com/gurock/trcli/files/10735834/cypress.txt)
<img width="1854" alt="image" src="https://user-images.githubusercontent.com/78972598/218829389-67ec9b34-2283-43fc-9603-deee63f78869.png">

### Desired behavior

The file gets uploaded to testrail

**Comment by d-rede** [comment]
Hello @awirl-foreflight 

Thanks for bringing this to our attention. 

From the logs there is clearly something wrong on the API call because it's sending the `type_id` as `1,`, which won't be considered an integer. Where and how are you passing the `type_id`?

**Comment by d-rede** [comment]
Glad to know you've overcome it! I'm closing this issue, but feel free to reopen in case you run into trouble again!
