### ISSUE TITLE
CASE ID is getting auto generated though we are providing an existing run id

### ISSUE THREAD

**Issue by Krishanu-Git** [gurock/trcli#128]
### TestRail CLI Version

1.4.2

### CLI Environment

Windows 11, Python 3.10

### TestRail Version

TestRail v7.5.6 Default (3001)

### TestRail Instance Type

Professional Cloud

### Current behavior

CASE ID is getting auto generated though we are providing an existing run id

command used:
**trcli -y -h "https://<INSTANCE>.testrail.io/"  -v -u "<USERNAME>" -p "<PASSWORD>"  --project "<PROJECT>"  parse_junit --case-matcher "property" --title "<SOME_TITLE>" --run-id 10 -f "output.xml"**

### Desired behavior

Expected not to generate any new case id when providing an existing run id should be taking the previous case ids allocated in that run id and update those with the Junit xml status

**NOTE:
If the run id is not provided then its creating a new run id and new case id and updating it as per status**

**Comment by Krishanu-Git** [comment]
@Testinator-X  I also tried to provide suite-id but still it tried to create new case ids with same test cases name

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/83639542/219712458-d95488dd-c3e0-4b83-a2b5-8cce9338e87f.png">

**Comment by sdbit04** [comment]
I support on this observation

**Comment by Krishanu-Git** [comment]
@Testinator-X Even while providing a particular suite-id and run-id it is still creating. new case ids with the same test case names in that same suite

![image](https://user-images.githubusercontent.com/83639542/219714535-ad7c7362-c02b-4024-b38a-4b4b7dffc21d.png)

**Comment by Testinator-X** [comment]
@Krishanu-Git I‘m not sure why you are tagging me here and how I can help you with this question. I‘m just a normal end user like you. IMHO you better might want to direct the question to someone more official like @d-rede

**Comment by Krishanu-Git** [comment]
@Testinator-X Apologies for tagging you I was not sure

**Comment by Krishanu-Git** [comment]
Closing this bug since I'm able to update the existing test case ids in test rail by removing **-y** as trcli option
