### ISSUE TITLE
Provide ability to publish results from multiple XML files

### ISSUE THREAD

**Issue by dominicwilliamslandmark** [gurock/trcli#129]
### What would you like the TestRail CLI to be able to do?

 It would be helpful if we're able to specify either a directory or multiple files for the -f flag instead of one single file. 

Alternatively could there be a --run-name similar to --run-id, which we can use if we don't know the run ID. This would allows us to run multiple scripts and upload the results to the same test run as we'd be able to specify the run name as we don't know the run ID that the cli creates.

Ultimately, it's just providing the ability to uploading result from multiple XML files to the same run id which will be created by the cli.

### Why is this feature necessary on the TestRail CLI?

We sometimes split our test runs in our pipeline which generates multiple XML files. Currently we're unable to create 1 test run which contains the results as the cli doesn't accept multiple result files.

In your article here - https://www.gurock.com/testrail/introducing-the-testrail-cli/ it suggests running the script multiple times which we can do, but if we create a run id on the first execution we don't know the run id for the second execution. The cli fails if you use the same name.

### Interested in implementing it yourself?

No

**Comment by mnataraj17** [comment]
Would be great if someone could work on this, have been trying to resolve this and it's hard to handle when we know only run title.
- It should go through all open Runs and match name of run and update test results to same run instead of creating new run if the run already exists.

**Comment by hai-ha** [comment]
@mnataraj17 To what I'm doing, we can choose from some other options while waiting for the enhancement:
1. Use [junit-report-merger](https://www.npmjs.com/package/junit-report-merger) to merge JUnit report files before publishing.
2. Write (bash/other) script to collect all suitable XML files and publish results in loop.
