### ISSUE TITLE
Cannot update test runs with --run-id flag

### ISSUE THREAD

**Issue by lscottnaim** [gurock/trcli#136]
### TestRail CLI Version

1.4.3

### CLI Environment

Python3.10, Ubuntu 22.04.2 LTS

### TestRail Version

TestRail v7.8.0 Default (1141)

### TestRail Instance Type

Professional Cloud

### Current behavior

Currently, attempting to update test runs with the --run-id flag with trcli returns the following:

Executed: `trcli -y -h https://{instance}.io --project "Software Test Automation" --username {username} --password {password} parse_junit --title "{unit} Automated Test Run" --run-id "3075" -f ./reports/*.xml'`

```xml
TestRail CLI v1.4.3
Copyright 2021 Gurock Software GmbH - www.gurock.com
Parse JUnit Execution Parameters
> Report file: ./reports/junit-report.xml
> Config file: None
> TestRail instance: https://OUR-INSTANCE.testrail.io (user: MY-EMAIL)
> Project: UNIT Software Test Automation
> Run title: Automated Test Run
> Update run: 3075
> Add to milestone: No
> Auto-create entities: True
Parsing JUnit report.
Processed 11 test cases in 1 sections.
Checking project. Done.
Adding missing suites to project Software Test Automation.
Found 11 test cases not matching any TestRail case.
Adding missing sections to the suite.
Adding missing test cases to the suite.
Adding test cases: 11/11, Done.
Updating run: https://OUR-INSTANCE.testrail.io/index.php?/runs/view/3075
Adding results: 0/11
Error during add_results. Trying to cancel scheduled tasks.

Aborting: add_results. Trying to cancel scheduled tasks.
Adding results: 0/11
No attachments found to upload.
Field :results cannot be empty but no valid tests or cases found
Deleted created test cases
Deleted created section
Deleted created suite
```

The results.xml in question is generated with pytest.
https://pastebin.com/yrnnTiw6

Said results.xml file can be uploaded without issue without the `--run-id` flag

### Desired behavior

Test runs are updated

**Comment by manastico** [comment]
Dear Team!
I noticed the same issue. I would like to create an empty testrun via api and during the executions I would create the xml files and at the end of the whole run, I would update the existing run with automatic testcase creation, but this is not possible, because the cli responses that there is no existing testcases in the run. By fixing this issue, I would be able to use the cli more effectively.
Regards,
Norbert

**Comment by Testinator-X** [comment]
For the problem that a test case created via the API is not automatically added to a run, even though the TestCase matches the dynamic filter settings of the run, I have filed a TestRail bug. If you want to vote for it, please write a mail to contact@gurock.com or use the contact form https://support.testrail.com/hc/en-us/requests/new and reference Request #265113. 

Btw. answer of the support staff was: 

> Hi,
>  
> Thanks for your email and i sincerely apologize for the inconvenience this may have caused.
>  
> Kindly use the GUI to create your TestCase for now; I will relate with the development team for further troubleshooting.
>  
> Apologies for the inconvenience.
>  
> Regards, 

The advice is pretty ridiculous as it is, considering that the API is used in particular for any automations. Updating the run manually via the GUI every time a new test case is automatically created via the API is impractical. 

@d-rede Do you have any idea how else this can be achieved via the API in a simple way?

**Comment by manastico** [comment]
I created a Java executable task which parses xml files and update testrun via API. It takes more time writing code, but it works and it is customizable.

**Comment by yuga-hashimoto** [comment]
I am also having the same problem
