### ISSUE TITLE
code first approach: cases created and test run created but no results uploaded in the testrun.

### ISSUE THREAD

**Issue by wafiqualtrics** [gurock/trcli#142]
### TestRail CLI Version

1.4.0

### CLI Environment

mac ventura 13.3.1

### TestRail Version

7.5.3.1000

### TestRail Instance Type

Enterprise Server

### Current behavior

cases created along with test runs but no result uploaded to the test run.

### Desired behavior

test result uploaded to the test run

**Comment by Testinator-X** [comment]
At first you should update TRCLI to the latest Version

**Comment by d-rede** [comment]
Hello @wafiqualtrics 

As Testinator-X suggested, please update the trcli to the latest version. If you could then retry uploading the results and, in case it fails, provide more info, such as the report and command you are using, we could provide further assistance.

Thanks

**Comment by d-rede** [comment]
Closing this issue due to lack of info, but don't hesitate to re-open or send in new evidence.
