### ISSUE TITLE
Add support for "Configurations"

### ISSUE THREAD

**Issue by UyttenhoveSimon** [gurock/trcli#146]
### What would you like the TestRail CLI to be able to do?

Hello,

Thanks for the trcli, it speeds up quite a bit the test data ingestion.
Would it be possible to add the ability to provide a "config" either in the junit xml or via the command line ?

I am referencing to the following:
https://support.testrail.com/hc/en-us/articles/7077298488340-Configurations

### Why is this feature necessary on the TestRail CLI?

I would like to display the same test in multiple environments and configurations would come handy.

Maybe there is another way of implementing the above use case that I would not be familiar with ?

### Interested in implementing it yourself?

No

**Comment by d-rede** [comment]
Hello @UyttenhoveSimon 

Currently the TestRail CLI only supports creating simple Test Runs. Managing Test Plans and Configurations is something we are trying to avoid for the sake of simplicity and to try to avoid users being overwhelmed and misusing the CLI.

Nevertheless, I will leave this ticket open for future consideration.
