### ISSUE TITLE
AZ devops No such command 'parse_junit' / trcli failed to load

### ISSUE THREAD

**Issue by talshachar20** [gurock/trcli#154]
Hey, since two days ago I'm getting this error on Azure devops (cannot reproduce manually) when trying to publish report 
I've tried with two versions : 1.4.2 / 1.5.0 

tried also install with this command : python3.10 -m pip install --force-reinstall trcli

Last week it worked perfectly . does anybody has an idea ? 

Error: No such command 'parse_junit'.
TestRail CLI v1.5.0
Copyright 2021 Gurock Software GmbH - www.gurock.com
trcli failed to load

**Comment by anastasijabulatova-toast** [comment]
I'm getting the same error

**Comment by jemishgopani** [comment]
it is happening because `pyserde` is updated to version `0.12.0` if you install `pip install pyserde==0.11.1` older version before `pip install trcli` it will work.

**Comment by talshachar20** [comment]
Works ! thank you very much @jemishgopani

**Comment by canadianveggie** [comment]
Is the problem here that `trcli` isn't versioning any of its dependencies in [setup.py](https://github.com/gurock/trcli/blob/main/setup.py)?

**Comment by jemishgopani** [comment]
Now this issue is fixed on `pyserde` version `0.12.1` 🚀

**Comment by pranit-kenjale** [comment]
Command 'parse_junit' is still not working for me with the below versions:
```
trcli==1.5.0
pyserde==0.12.1 or pyserde==0.11.1
```
Is there any workaround ?

**Comment by d-rede** [comment]
I'm sorry to know an external dependency managed to break the CLI. 

Dependency management is set to be improved in the next release and we will track it's resolution in issue https://github.com/gurock/trcli/issues/137.

Closing this issue.
