### ISSUE TITLE
Don't require title (run_name) when updating an existing testrun

### ISSUE THREAD

**Issue by othererik** [gurock/trcli#171]
### What would you like the TestRail CLI to be able to do?

I want the `title` value to be optional when updating an existing test run. When the user provides a `run_id`, the only time they should be required to enter the test run name is if they intend to update it to something new.

### Why is this feature necessary on the TestRail CLI?

The behavior of trcli changed between 1.5 and 1.6. In 1.5, the title field was ignored when a test run was updated (vs. created). In 1.6, the field is always used.    This led to some confusion as we began changing run names unintentionally in some cases.  It seems more straightforward not to require the field when the operation doesn't need it. 

### More details

I have a proposed solution: [optional_title_if_runid](https://github.com/gurock/trcli/compare/main...othererik:trcli:optional_title_if_runid)

It was tested to support updating and not updating use cases.  If this issue is accepted I'll look into any needed tests, etc.

### Interested in implementing it yourself?

Yes

**Comment by bitcoder** [comment]
It makes sense to me at first sight; as we currently parse JUnit and Robot Framework files, we need to support both of them

**Comment by othererik** [comment]
@bitcoder, Awesome!  Thank you for taking this on. I'll pull the branch and give it a shot.

**Comment by othererik** [comment]
Confirmed title update and optional title behaviors.   Worked as I hoped.  I'm sorry I didn't have time to come back and commit this PR myself.    Seems great to me. Thanks again!

**Comment by bitcoder** [comment]
Will make it part of v1.7.0 release to be addressed soon
