### ISSUE TITLE
Error detected while checking a project: <list of projects>

### ISSUE THREAD

**Issue by gourianova91** [gurock/trcli#177]
Background:
Python **3.12.0**
TestRail CLI **1.6.2**
TestNG, Java
We have our company TestRail server (non-admin user)

**_Error description:_**
` trcli -y --project "My project name 1" --project-id 1 --insecure -c "trcli-config.yml" -v parse_junit -f "./sample_reports/TEST-TestSuite.xml" 
TestRail CLI v1.6.2
Copyright 2023 Gurock Software GmbH - www.gurock.com
Parser Results Execution Parameters
> Report file: ./sample_reports/TEST-TestSuite.xml
> Config file: trcli-config.yml
> TestRail instance: https://testrail.server.com/testrail/ (user: username)
> Project: My project name 1
> Run title: TestNG Automated Test Run
> Update run: No
> Add to milestone: No
> Auto-create entities: True
Parsing JUnit report.
Processed 1 test cases in 1 sections.
Checking project.
**** API Call
method: GET
url: https://testrail.server.com/testrail/index.php?/api/v2/get_projects
response status code: 200
response body: b'USER AUTHENTICATION SUCCESSFUL!\n[{"id":1,"name":"My project name 1","announcement":null,"show_announcement":false,"is_completed":false,"completed_on":null,"suite_mode":3,"url":"https:\\/\\/testrail.server.com\\/testrail\\/index.php?\\/projects\\/overview\\/1"},{"id":2,"name":"My project name 2","announcement":null,"show_announcement":false,"is_completed":false,"completed_on":null,"suite_mode":3,"url":"https:\\/\\/te
strail.server.com\\/testrail\\/index.php?\\/projects\\/overview\\/2"}]'
****

Error detected while checking a project: b'USER AUTHENTICATION SUCCESSFUL!\n[{"id":1,"name":"My project name 1","announcement":null,"show_announcement":false,"is_completed":false,"completed_on":null,"suite_mode":3,"url":"https:\\/\\/testrail.server.com\\/testrail\\/index.php?\\/projects\\/overview\\/1"},{"id":2,"name":"My project name 2","announcement":null,"show_announcement":false,"is_completed":false,"completed_on":null,"suite_mode":3,"url":"https:\\/\\/te
strail.server.com\\/testrail\\/index.php?\\/projects\\/overview\\/2"}]''
`

The response returns correct name for my "My project name 1" as well as I have checked in Postman.
So I don't know what the issue is with my project?

**Comment by bitcoder** [comment]
Well, it's a bit strange.
1. have you tried using just the `--project`  argument or the `--project-id`  argument (not both at the same time)?
2. it seems the API is return "USER AUTHENTICATION SUCCESSFUL!" before the JSON content.. which if true, is strange. Do you see that response if you use Postman or even put the URL  "https://testrail.server.com/testrail/index.php?/api/v2/get_projects" in your browser?

**Comment by gourianova91** [comment]
Hi @bitcoder 

> have you tried using just the --project argument or the --project-id argument (not both at the same time)?

yes, 
**-project argument**  - error i the same
**--project-id argument** - error the same  and "**Please specify the project name using the --project argument.**"

> it seems the API is return "USER AUTHENTICATION SUCCESSFUL!" before the JSON content.. which if true, is strange. Do you see that response if you use Postman or even put the URL "https://testrail.server.com/testrail/index.php?/api/v2/get_projects" in your browser?

Yes the same in Postman 
![image](https://github.com/gurock/trcli/assets/5639777/6f074c6a-e16b-4404-81b3-3de397281d39)

> I tried replicate your call, having similar names for the projects but without success

The names for projects I can not put here - but as you can see I have in API response more than one project assigned on me

**Comment by bitcoder** [comment]
What testrail version do you have?

**Comment by bitcoder** [comment]
thanks @gourianova91 .
As this is related to a problem on the TR side, on the API call related response, I kindly ask you to [raise a support ticket on TestRail](https://support.testrail.com/hc/en-us/requests/new) so the support team can assist you on this.
On the CLI side, as soon you have a fix/update on the TR you should be good to go.
I'll leave this issue open for some time even though the error is not CLI related.

**Comment by gourianova91** [comment]
@bitcoder thanks

**Comment by gourianova91** [comment]
@bitcoder but unfortunately I can not raise that request, because our company anyway will not update their Tetsrail version even there will be a bug fix.

**Comment by bitcoder** [comment]
@gourianova91  can you try using the version attached ahead?


```bash
python3 -m pip uninstall trcli -y 
python3 -m pip install trcli-1.6.3.tar.gz
````

[trcli-1.6.3.tar.gz](https://github.com/gurock/trcli/files/13619451/trcli-1.6.3.tar.gz)

**Comment by gourianova91** [comment]
Hi @bitcoder 

The error is the same with trcli-1.6.3

**Comment by bitcoder** [comment]
@gourianova91 just to clarify, have you tried with the patched .tar.gz file I provided or with the official 1.6.3 version?

**Comment by gourianova91** [comment]
@bitcoder 

sorry didn't notice your attahcment

**Comment by bitcoder** [comment]
Right, then the problem was overcome. The error message you're getting is totally unrelated with this issue; you need to configure an `automation_id` field as stated in the [documentation]( https://github.com/gurock/trcli#1-using-automation-id-code-first-approach): 
Let me know if you got it working after that.

**Comment by gourianova91** [comment]
@bitcoder 

Thank you a lot!

Our company Testrail support added that field by my request - so now I can see the created Test run in Testrail.

The issue was solved.
