### ISSUE TITLE
After test results junit file uploaded,  test suites and cases created again with the same names

### ISSUE THREAD

**Issue by mattmoana** [gurock/trcli#178]
### TestRail CLI Version

TestRail CLI v1.4.3

### CLI Environment

MAC OS VENTURA

### TestRail Version

TestRail v8.0.1 Default (1033)

### TestRail Instance Type

Professional Cloud

### Current behavior

I run playwright tests on my machine.
After it was done It generats junit xml file
Then I run. trcli -y -h command to load results to testrail
It checks for existent suite cases etc and when does not find any similar ones - creates test run and new test suite with test cases.

**Now the problem:** When I run it again exactly the same junit with all data exactly the same - instead of just creating only new test run I also get another test suite with test cases with exactly the same names. 

So to summarize every time I upload junit report I have exactly the same test cases and test suites created again and again instead of checking for existing ones.

So I keep getting this in the console: 
_Found 7 test cases not matching any TestRail case._
_Adding missing sections to the suite.
Adding missing test cases to the suite._

What could be the reason It cannot recognize already existent cases? I tried everything that is described in testrail faq etc. Please advice

### Desired behavior

If junit report contains names of test suites and test cases that already exist in testrail - it should not create test suites and test cases again and only create a new test run

### More Details

<img width="1262" alt="Screenshot 2023-11-04 at 12 57 52" src="https://github.com/gurock/trcli/assets/35107712/815aa57b-1169-4d6f-a542-57e8e1aa79ed">

**Comment by Testinator-X** [comment]
The latest version of trcli is v1.6.2. Does the problem also occur with this version?
Have you tried using the `--suite-id` or `--suite-name` options to specify which suite should be used exactly?

What exactly does your complete trcli command look like?

**Comment by mattmoana** [comment]
> suite

@Testinator-X thank you, updating to latest version fixed the issue. Case solved :)
