### ISSUE TITLE
TRCli - Test Suite Named - io.cucumber.core.plugin.JUnitFormatter is considered while adding tests to Test Rail

### ISSUE THREAD

**Issue by sjoshidw** [gurock/trcli#179]
### TestRail CLI Version

1.6.1

### CLI Environment

Windows 10, Python 3.11.5

### TestRail Version

TestRail v8.0.1 Default (1033)

### TestRail Instance Type

Professional Cloud

### Current behavior

We are using TrCli utility - https://github.com/gurock/trcli to upload our tests via jenkins pipeline scripts or local results via following command - 

trcli --insecure --verbose -y -c "testrailconfig.yaml" parse_junit -f "./test-output/junitreports/TEST-runner.runner.xml" --suite-name "tests.LoginTests" 

I had followed your documentation where there is a option of providing --suite-name but it can replace the test suite name and class but We need to change the test suite root name of junit file - which is right now Junit generated file is "io.cucumber.core.plugin.JUnitFormatter"

### Desired behavior

Can TRCLi provide any option to customize this root test suite? because of this, we are getting unnecessary sections created on the test rail project which require attention.

### More Details

Junit file (see image)- 

![image](https://github.com/gurock/trcli/assets/127960361/3a40fed7-205b-454d-a1f5-cd24dd914e74)

Test Rail Config contains see image:
![image](https://github.com/gurock/trcli/assets/127960361/7f227523-7b46-41bd-afea-9f444c874333)

**Comment by Testinator-X** [comment]
The latest version of trcli is v1.6.2. Does the problem also occur with this version?

**Comment by sjoshidw** [comment]
Thanks for the response, I have upgraded pip package to v1.6.2 issue still persistent under Test Cases section - 
<img width="926" alt="image" src="https://github.com/gurock/trcli/assets/127960361/e5d3046c-ace9-4c6b-a34f-565bfc63489a">

**Comment by bitcoder** [comment]
@sjoshidw,
can you please clarify some points?
1. is your target project of type "single repository" or "multiple suite"?
2. how many sections do you get created in TestRail? Just one right? (i.e., "io.cucumber.core.plugin.JUnitFormatter")?
3. the section(s) that was/were created is/are empty? or do they have test cases within them?
4. if I got you correctly, what you would like to have would be a way to define the name of the section where those tests should be added to in TestRail, right? what exactly would you like to have in TestRail side?

**Comment by sjoshidw** [comment]
Okay thanks for updates, will get back!

**Comment by bitcoder** [comment]
@sjoshidw were you able to have a look at this?

**Comment by bitcoder** [comment]
Any feedback please? Or else I'll close the issue assuming it was implicitly fixed

**Comment by sjoshidw** [comment]
I was on planned leaves, let me see in the next 24 hours! Thanks!

**Comment by bitcoder** [comment]
@sjoshidw happy new year first of all :) Any news on this topic?

**Comment by bitcoder** [comment]
I'm closing this issue for lack of feedback. If the problem arises, please raise a new issue
