### ISSUE TITLE
Upload tests to trcli is failing 

### ISSUE THREAD

**Issue by RahateSwati** [gurock/trcli#180]
### TestRail CLI Version

1.4.3

### CLI Environment

python 3.10

### TestRail Version

8.0.1

### TestRail Instance Type

Enterprise Server

### Current behavior

**Trying to add missing tests to the section it just created but the test upload is failing for some unknown reason and then it deletes the section once and again tried to delete it but gets 400.**

LOGS BELOW

**** API Call
method: POST
url: https://<>.testrail.io/index.php?/api/v2/add_case/5376
payload: {'title': 'OD_Products_Api_Access_Control -xx', 'custom_automation_id': 'OD_Products_Api_Access_Control.OD_Products_Api_Access_Control - xx'}

**Error during add_case. Trying to cancel scheduled tasks.

Aborting: add_case. Trying to cancel scheduled tasks.**

....

**** API Call
method: POST
url: https://<>.testrail.io/index.php?/api/v2/add_case/5376
payload: {'title': 'OD_Products_Api_Access_Control -xxx api', 'custom_automation_id': 'OD_Products_Api_Access_Control.OD_Products_Api_Access_Control -xxx'}

**** API Call
method: POST
url: https://<>.testrail.io/index.php?/api/v2/add_case/5376
payload: {'title': 'OD_Products_Api_Access_Control - xx', 'custom_automation_id': 'OD_Products_Api_Access_Control.OD_Products_Api_Access_Control - xx'}

**** API Call
method: POST
url: https://<>.testrail.io/index.php?/api/v2/add_case/5376
payload: {'title': 'OD_Products_Api_Access_Control - xxxx api', 'custom_automation_id': 'OD_Products_Api_Access_Control.OD_Products_Api_Access_Control - xxx'}

Adding test cases: 0/19
Your upload to TestRail did not receive a successful response from your TestRail Instance. Please check your settings and try again.

**** API Call
method: POST
url: https://<>.testrail.io/index.php?/api/v2/delete_section/5376

**** API Call
method: POST
url: https://<>.testrail.io/index.php?/api/v2/delete_section/5376
response status code: 400
response body: {'error': 'Field :section_id is not a valid section.'}
****
Unable to delete created section: Field :section_id is not a valid section.
ukc

### Desired behavior

All the missing tests should be uploaded without any issue, 
If there is any error it should clearly state the error and how to fix it 

(right now I don't know what's going wrong or how to fix it)

**Comment by Testinator-X** [comment]
The latest version of trcli is v1.6.2. Does the problem also occur with this version?

**Comment by bitcoder** [comment]
Closing in the next days unless further feedback is provided
