### ISSUE TITLE
TestRail CLI creates new empty sections in Testrail project test cases 

### ISSUE THREAD

**Issue by Jackagency** [gurock/trcli#181]
### What would you like the TestRail CLI to be able to do?

It would be great if TestRail CLI could match with the sections I've already created in TestRail and not create new empty sections every time I run it. I use TypeScript + Playwright.

### Why is this feature necessary on the TestRail CLI?

At the moment, when using TypeScript + Playwright, I am unable to maintain a neat and readable set of test cases, as I am forced to either use the suggested section names such as tests/api-tests/deposit/invoiceless/test.ts, which is not very convenient and readable, or to put up with empty sections in the test case area, which significantly degrade the experience of using TestRail.

### More details

Here's an example of how I had to format the empty sections because there simply was no other choice.
<img width="1487" alt="Снимок экрана 2023-11-08 в 5 46 03 PM" src="https://github.com/gurock/trcli/assets/56089621/1d965ca3-cde7-4877-9e98-036ab533550f">

### Interested in implementing it yourself?

No

**Comment by bitcoder** [comment]
1. Which TR version and CLI version are you using?
2. what type of project are you using?
3. can you share an example of the CLI call you made?

**Comment by Jackagency** [comment]
1. TR version 6.2.3.114, CLI version 1.6.1
2. My project is TypeScritp + playwright (or clarify what you meant)
3. `trcli -y -h "https://testrail.io" --project "project" --username "username" --password "password" parse_junit -f "./test-results/junit-report.xml" --title "API Autotests Test Run" --section-id "52" --case-matcher "name" --close-run`

**Comment by bitcoder** [comment]
Thanks for the feedback @Jackagency .
On the type of project, I was referring to:

- Single Repository
- Single Repository with Baseline Support
- Multiple Test Suites

Which one are you using?

**Comment by Jackagency** [comment]
1. I'm not sure that i understand it but i guess it's Single Repository

2. I am experiencing an issue with the TestRail CLI where it is unable to locate my existing folders containing test cases. Instead, it creates new folders modeled after my automated test project. Specifically, while the CLI recognizes individual test cases by their IDs, my testing framework (Playwright) does not have an equivalent entity for sections or folders containing test cases. As a result, when generating reports, the CLI accurately places the correct test cases into the report but simultaneously creates missing folders in the test case repository. This seems to happen because the CLI cannot detect these folders, as there is no parameter in the report that would link the test cases to their respective folders or sections in TestRail. 
I explained my case on TestRail youtube channel and here is the support response ""Thank you for reaching out! The CLI does not support your use case for now. Please, create an issue in GitHub so we can further improve the CLI features to meet your needs: https://github.com/gurock/trcli""

3. I ran one test as an example for the report and removed the details and names of the cases, but the structure of the report looks like this.
<img width="1001" alt="Снимок экрана 2023-12-05 в 6 39 02 PM" src="https://github.com/gurock/trcli/assets/56089621/7ae7edcc-e0c5-40d0-aecb-5859ef4587ae">

4.Yes, ID 52 corresponds to the 'Playwright sections' section. I created it to store the empty sections generated by TestRail CLI, so it doesn't clutter my project and at least keeps them in one place. It doesn't generate them anew each time; it creates a section for every test file in the project, which I don't need, as I already have manually created sections. If I add a new file to my automated test project, it generates a new section named after the file in the project. This is the problem: I can't seem to communicate to it that the section already exists, and there's no need to create new ones.

**Comment by Testinator-X** [comment]
1. see also https://support.testrail.com/hc/en-us/articles/7076923860244-Projects-and-their-types#how-to-change-from-one-project-type-to-another-0-1 and https://www.testrail.com/videos/project-types for an explanation of possible TestRail project types.

**Comment by bitcoder** [comment]
Right now, the CLI will create sections based on the test suite names. In Playwright, the JUnit XML report uses the name of the source file containing the tests.
1. Whenever you import the results, you get those sections created without any tests inside them?
2. I think you have you tests all annotated with "Cxx", correct? If so, these tests already exist in TestRail in some suites/folders, like the "Payout", "Invoices", etc, as you have in your screenshot. Did it get it right?
3. From my understanding,  if the previous point is true, then you basically don't want the  suites to be created as the test cases and the respective suites already exist, righh?

**Comment by bitcoder** [comment]
Got it. I agree that create empty sections doesn't make sense. Let me think on a solution.
