### ISSUE TITLE
 --case-fields not working when I attempt to push data to some of the fields (i.e. Type, custom-field in Testrail )

### ISSUE THREAD

**Issue by jayslbrte** [gurock/trcli#205]
### TestRail CLI Version

8.0.3

### TestRail Version

8.0.3

### TestRail Instance Type

Professional Cloud

### Current behavior

 --case-fields not working when I attempt to push data to some of the fields (i.e. Type, custom-field in Testrail )
 
 TRcli is not pushing data to my case fields  like it should do 
  --case-fields "automation_status:Automated" \
  --case-fields "type:Integration Test" \

### Desired behavior

I want to push data to my case fields together with the results from junit 
I want below 
 --case-fields "automation_status:Automated" \
  --case-fields "type:Integration Test" \

**Comment by bitcoder** [comment]
Hi @jayslbrte ,
1. can you please provide a sample of the JUnit XML report you're submitting  and the exact command line?
2. can you also detail the type of these fields on TestRail?

**Comment by jayslbrte** [comment]
**1. JunitXML report** 
  <testsuite name="Sample.Tests.dll" tests="4" skipped="0" failures="1" errors="0" time="0.5011519" timestamp="2024-02-06T03:33:23" hostname="XXXXXX" id="0" package="XXXXXXX">
    <properties />
    <testcase classname="Sample.Tests.V1.Forms.Validators.CreateFormRequestValidatorTests" name="Sample.Tests.V1.Forms.Validators.CreateFormRequestValidatorTests.GivenValidDetails_WhenValidatingForm_ThenNoErrors" time="0.0450940">
      <failure type="failure" message="System.Exception : I am an issue">at Sample.Tests.V1.Forms.Validators.CreateFormRequestValidatorTests.GivenValidDetails_WhenValidatingForm_ThenNoErrors() in /Users/XXXXX/Work/Code/Tests/V1/Validators/CreateFormRequestValidatorTests.cs:line 1</failure>
    </testcase>
    <testcase classname="Sample.Tests.V1.Forms.Validators.CreateFormRequestValidatorTests" name="Sample.Tests.V1.Forms.Validators.CreateFormRequestValidatorTests.GivenEmptyString_WhenValidatingName_ThenMandatoryErrorForName(&quot;&quot;)" time="0.1520220" />.....
    
   **2.the type of these fields on TestRail?**
   
![image](https://github.com/gurock/trcli/assets/90076252/acc1291f-c1c7-424f-8e6f-b1a9a4c6ba2b)
![image](https://github.com/gurock/trcli/assets/90076252/f71e2f54-1c24-4e43-aeee-639d3c9dfc43)

**Comment by jayslbrte** [comment]
@Testinator-X , Thank you for your help. 
it works using: 
  --case-fields "custom_automation_status:2" \
  --case-fields "type_id:14"

**Comment by bitcoder** [comment]
thanks I'll close this after reviewing current docs

**Comment by jayslbrte** [comment]
@Testinator-X  is there a way  trcli can allow you to organise your new test cases by it creating new test folders using testcase names instead testsuite name? 

```
<testsuites>
  <testsuite name="Tests.suite" tests="4" skipped="0" failures="1" errors="0"
  <testcase classname="Tests.V1.Validators.CreateRequest" name="Tests.V1.Validators.CreateRequest.GivenCoolString_WhenValidatingName_ThenMandatoryErrorForName(....
  <testcase classname="Tests.V1.Validators.CreateRequest" name="Tests.V1.Validators.CreateRequest....
  <testcase classname="Tests.V1.Validators.CreateRequest" name="Tests.V1.Validators.CreateRequest....
  <testcase classname="Tests.V1.Validators.CreateRequest" name="Tests.V1.Validators.CreateRequest....
```

**Comment by bitcoder** [comment]
That's non configurable
