### ISSUE TITLE
TRCLI failed on the ci cd

### ISSUE THREAD

**Issue by anastasijabulatova-toast** [gurock/trcli#211]
### TestRail CLI Version

trcli-1.9.1

### CLI Environment

Linux x86_64, python3.10

### TestRail Version

TestRail v8.0.3 Default (3067)

### TestRail Instance Type

Professional Cloud

### Current behavior

14:15:14  + trcli -n -c trcli-config.yml -u **** -p **** parse_junit --case-matcher name --suite-id 8160 -f test-results/junit-report.xml
14:15:14  Traceback (most recent call last):
14:15:14    File "/home/jenkins/.local/bin/trcli", line 5, in <module>
14:15:14      from trcli.cli import cli
14:15:14    File "/home/jenkins/.local/lib/python3.10/site-packages/trcli/cli.py", line 3, in <module>
14:15:14      from beartype.typing import List, Union
14:15:14  ModuleNotFoundError: No module named 'beartype.typing'

### Desired behavior

trcli failed on ci with the import error

**Comment by mattmoana** [comment]
yup i have same error in my pipeline

**Comment by medgartest** [comment]
same error on Mac (on cmd line - not Jenkins or other ci)
first install so wasn't sure if I was missing something but seems same error as others

fyi can be reproduced without parameters

trcli
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/trcli", line 5, in <module>
    from trcli.cli import cli
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/trcli/cli.py", line 3, in <module>
    from beartype.typing import List, Union
ModuleNotFoundError: No module named 'beartype.typing'

**Comment by bitcoder** [comment]
thanks for reporting; will have a look it shortly; not sure why this wasnt caught on the pipeline

**Comment by medgartest** [comment]
upgrading Beartype seems to help

pip3 install beartype --upgrade

**Comment by bitcoder** [comment]
I found the typo
