### ISSUE TITLE
Unable to parse field title in TestRailCase tag. Title is empty.

### ISSUE THREAD

**Issue by marksaxer-cbs** [gurock/trcli#218]
### TestRail CLI Version

1.9.4

### CLI Environment

Python 3.11.8

### TestRail Version

v8.0.3 Default 3070

### TestRail Instance Type

Enterprise Cloud

### Current behavior

If a junit-report.xml file contains a testcase name that exceeds 100 characters, the entire results upload fails.

Command
```
> trcli -y -h <host> --project '<project>' -u 'test.user@email.com' -k $API_TOKEN \
  parse_junit \
  --suite-id 123 \
  --run-id 1234 \
  -f "junit-report.xml"
TestRail CLI v1.9.4
Copyright 2024 Gurock Software GmbH - www.gurock.com
Parser Results Execution Parameters
> Report file: junit-report.xml
> Config file: None
> TestRail instance: https://host/ (user: test.user@email.com)
> Project:<project>
> Run title: None
> Update run: 1234
> Add to milestone: No
> Auto-create entities: True
Parsing JUnit report.
Unable to parse field title in TestRailCase tag. Title is empty.
```

Contents of "junit-report.xml"
```
<?xml version="1.0" encoding="utf-8"?>
  <testsuites><testsuite name="pytest" errors="0" failures="0" skipped="0" tests="1" time="1.888" timestamp="2024-03-11T15:40:16.888055" hostname="BLAHBLAHBLAH">
    <testcase classname="services.service.tests.boring_test" name="test_boring_123456789009876543211234567890098765432112345678900987654321123456789009876543211234567890" time="1.871">
    <properties>
      <property name="testrail_attachment" value="logs/service/boring_test/test_boring__2024_03_11T15_40_16.log" />.</properties>
    </testcase>
  </testsuite>
</testsuites>
```

The failure is thrown at: https://github.com/gurock/trcli/blob/62f87f2943bb649737c252c1354f5a366d65fc0d/trcli/readers/junit_xml.py#L167-L174

because `TestRailCaseFieldsOptimizer.extract_last_words` will return an empty string when `case_name` does not contain any delimiters `[' ', '\t', ';', ':', '>', '/', '.']` and exceeds `MAX_TESTCASE_TITLE_LENGTH` or 100 characters.

It appears that, at least in the version we are using, TestRail UI accepts more than 100 characters for a test case title.

### Desired behavior

I would like to be able to increase this limit or modify `extract_last_words` to always return a string with a length > 1. This could be accomplished either by:
- including the `_` underscore character in the delimiters list
- increasing the value of `MAX_TESTCASE_TITLE_LENGTH` to match the users version of TestRail max title length
- use the last `MAX_TESTCASE_TITLE_LENGTH` characters within the string if the string exceeds `MAX_TESTCASE_TITLE_LENGTH`

If those solutions are rejected, I'd like to implement:
- better error handling to inform the user of the character limit
- continue-on-error in order to upload as many results as possible

**Comment by marksaxer-cbs** [comment]
This ticket duplicates #207 and was addressed in #209 by @bitcoder. However, I think the solution could be improved further. I am happy to pick up the work if we have a consensus on the solution

**Comment by mist3r3** [comment]
We have the exact same issue, The problem as well is that the error thrown is a bit irrelevant...
"Unable to parse field title in TestRailCase tag. Title is empty."

**Comment by bitcoder** [comment]
After thinking a bit more I think just following the next approach works better:

`use the last MAX_TESTCASE_TITLE_LENGTH characters within the string if the string exceeds MAX_TESTCASE_TITLE_LENGTH`



Can you please both of you try this version and give some feedback on it?


[trcli-1.9.5.tar.gz](https://github.com/gurock/trcli/files/14605924/trcli-1.9.5.tar.gz)

**Comment by khvirtru** [comment]
encountered same error here.

**Comment by bitcoder** [comment]
feedback would be appreciated to assess if my fix addresses your needs

**Comment by marksaxer-cbs** [comment]
The fix looks good to me and the implemented solution, in my opinion, is more ideal than adding `_` to the delimiters list.

**Comment by mist3r3** [comment]
@bitcoder it's working for me, Thanks!! :)

**Comment by mist3r3** [comment]
@bitcoder actually now that I checked it, I get truncated test case names...

**Comment by mist3r3** [comment]
Well I get for example testing_this_as_an_example_for_testrail_trcli_in_github_test_test_test_tes_test
it is truncating the beginning.. so I would get sting_this_as_an_example_for_testrail_trcli_in_github_test_test_test_tes_test as the test case name...

I would expect to see the whole test case name... At least in the UI.

**Comment by bitcoder** [comment]
@mist3r3  can you pls share your JUnit XML report?

**Comment by mist3r3** [comment]
[test-report.xml.zip](https://github.com/gurock/trcli/files/14654497/test-report.xml.zip)

**Comment by bitcoder** [comment]
Well, I've updated the PR.
Can you please try this one?
@mist3r3 , meanwhile I resubmitted the junit report you provided where I also did a small change.
<img width="1313" alt="image" src="https://github.com/gurock/trcli/assets/553801/f2be236e-ab93-4660-938a-225dc0b5d013">

[trcli-1.9.5.tar.gz](https://github.com/gurock/trcli/files/14655718/trcli-1.9.5.tar.gz)

**Comment by bitcoder** [comment]
I'm assuming it works for you right?

**Comment by veyselkaran** [comment]
I still see the issue that exist. 
```
Adding test cases: 8/126
Field :custom_automation_id is too long (250 characters at most).
```
