### ISSUE TITLE
Network error when importing test case from a specific test suite

### ISSUE THREAD

**Issue by rvignon** [gurock/trcli#224]
### TestRail CLI Version

1.9.0

### CLI Environment

Windows 10, python 3.11.6

### TestRail Version

7.4

### TestRail Instance Type

Enterprise Server

### Current behavior

**Prerequisite :** 
- Test suite run with Robot Framework 6.1.1
- output.xml generated by RF

**Steps**
- Import test case in Test Rail using the CLI with following command : 
` trcli --config .\variables_conf\trcli_config.yaml parse_robot --title "Test Import" --suite-id 8 -f <path_to_output.xml> --case-matcher "auto"`

**Actual results**
I get the following error : 
Error occurred while checking for 'missing test cases': 'Upload to TestRail failed due to a network error. Please make sure you have a valid network connection then try again.' 

### Desired behavior

Test run is created with all the test cases from the test suite specified in the command line

### More Details

When using another test suite with less test cases it is working. 
Currently the response from the request listing all the test cases from the test suite that does not work is 9.3 MB
It doesn't whatever the machine and local time response of the request (testing from a browser for example)

**Comment by bitcoder** [comment]
can you please try with latest version (1.9.5)?

**Comment by rvignon** [comment]
Issue has been fixed by settings a timeout to 120s to wait for the answser of the webservice. 
NOTE that a curl command is executed in less than 10 seconds when with test rail API bindings for Python it takes more than 1 minute.
Can you explain this difference ?

**Comment by bitcoder** [comment]
> Issue has been fixed by settings a timeout to 120s to wait for the answser of the webservice. NOTE that a curl command is executed in less than 10 seconds when with test rail API bindings for Python it takes more than 1 minute. Can you explain this difference ?

Well, this project is about the TR CLI tool; I'm unable to provide o other projects like API bindings for Python, sorry.
Concerning the timeout, how did you defined it? Was it with "-t" parameter on the trcli command line?
If so, maybe you need to enable `verbose` mode in the command line to depict the call that is taking longer
