### ISSUE TITLE
No option to point to file path that contains a couple of reports or 1 report in 1 time

### ISSUE THREAD

**Issue by InnaPery** [gurock/trcli#239]
### TestRail CLI Version

1.9.5

### CLI Environment

Win 10

### TestRail Version

v7.5.3.1000

### TestRail Instance Type

Professional Cloud

### Current behavior

i am running the following cli:
trcli -h https://testrail.##  --project "##"  --username ##  --password ##  parse_junit --title "Cypress Automated Test Run" --suite-name "##" --case-matcher "name" -f "./path/results-*.xml"
the folder 'path' can contain 1 or many files that start with 'results-'
the bug is: in such way of running it works only if there are a couple of files in 'path' folder, if there is 1 file - it fails!

### Desired behavior

-f "./path/results-*.xml" should work with each number of files in 'path' folder

**Comment by acuanico-tr-galt** [comment]
Hi @InnaPery thank you for raising this issue and apologies for replying a bit late. We have recently implemented a glob parsing fix on the latest release and should have fixed this issue. Thank you.
