### ISSUE TITLE
CLI command is not creating the testcese in Testrail in sequential Order. It is creating in uneven sequence. I have re-arrange them manually on testrail.

### ISSUE THREAD

**Issue by manojbabutadikonda** [gurock/trcli#249]
### TestRail CLI Version

v1.9.5

### CLI Environment

macOS

### TestRail Version

TestRail v8.0.4 Default (7036)

### TestRail Instance Type

Enterprise Server

### Current behavior

CLI command is not creating the testcese in Testrail in sequential Order. It is creating in uneven sequence. I have to re-arrange them manually on testrail.

### Desired behavior

Testcases should be created on testrail in the same sequential order in which they are run.

I have attached the .xml file in which the sequence is correct. But the sequence is not the same sequence of testcases creation on testrail(attached screenshot for the same as well.)

### More Details

[TEST-TestSuite.xml.zip](https://github.com/user-attachments/files/16313585/TEST-TestSuite.xml.zip)
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/3d019b5f-c584-44f8-97c2-a63d14c8d739">

**Comment by Testinator-X** [comment]
I think that this will be unavoidable due to multithreading. Have you tried disabling multithreading as described in the documentation?
https://github.com/gurock/trcli#multithreading

**Comment by manojbabutadikonda** [comment]
@Testinator-X Thankyou for the info. Yes, I missed to update the multithreading thing.

& I couldnt find settings.py anywhere after i installed trcli. May i know where to find it. I could find it in the git repo - but not anywhere in the installed folder. please help on this

**Comment by Testinator-X** [comment]
I'm sorry, as I'm not a macOS user, I can't tell you where pip packages are installed on this system.
Was wird ausgegeben, wenn du den Befehl `pip install --upgrade trcli` ausführst?

On Windows the default path is:  `C:\Python<version>\Lib\site-packages\trcli\settings.py`

**Comment by manojbabutadikonda** [comment]
@Testinator-X Thankyou so much. I was able to navigate to "trcli" from site-packages and was able to update settings.py.

On My mac, is was located at "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/trcli/settings.py"

Im closing this ticket.

1s again thanks a lot @Testinator-X
