### ISSUE TITLE
Test Run description wiped out when adding test results to test run

### ISSUE THREAD

**Issue by smartuuu** [gurock/trcli#250]
### TestRail CLI Version

v1.9.5

### CLI Environment

Win 11 pro

### TestRail Version

TestRail v6.0.0.4140

### TestRail Instance Type

Enterprise Server

### Current behavior

Hello! 
I'm using TRCLI with Robot Framework. 
I found when I post test results using trcli to the respective test run, the test run's description in Testrail is completely wiped out.
This is the command I'm using:
trcli -n ^
-h "http://testrail.xxxxxx/" ^
--project "XXXXXXXXXX" ^
--username "XXXXXXXXXXXXXX" ^
--key XXXXXXXXXXXXXXXXXXXXXX ^
parse_robot ^
--title "XXXXXXXXXXXXXXXXXXXXXX" ^
--run-id "XXX" ^
--case-matcher "name" ^
-f output.xml

### Desired behavior

To keep the test run's description intact.

**Comment by acuanico-tr-galt** [comment]
We have added a new PR for this issue. This might be shipped with TRCLI version 1.9.8 :)

**Comment by smartuuu** [comment]
Thank you! Just verified and it works!
