### ISSUE TITLE
How to pass the custom field?

### ISSUE THREAD

**Issue by m-sternak** [gurock/trcli#254]
### What would you like the TestRail CLI to be able to do?

created a mandatory field for the test case "product" in TestRail. Now when importing playwright results via trcli I need to pass the the value of this field. How to identify the proper name if the custom field an it's value?
The field is mandatory, so it's necessary to have it in the trcli command.

### More details

![image](https://github.com/user-attachments/assets/201f018b-ce23-4ec8-8dbf-1ced8cc0f57e)

### Interested in implementing it yourself?

No

**Comment by jakec-routable** [comment]
@m-sternak Assuming you want to send the same value for all results of an upload, you just need to use the `--result-fields` flag of the `parse_junit` command. For example, if your custom result field system name is `product`, then you would invoke the trcli command similar to this:
```
trcli -h <host> --project <project_name> -u <user> -p <pass> parse_junit --result-fields "custom_product:<value" -f results.xml
```

**Comment by m-sternak** [comment]
@jakec-routable this is the second case, I need to create a new test case while importing results. 
So, I need to use the `--case-fields` parameter but how to I determine the name of my custom field? Assuming that the system name = product, would that be `custom_product` ?

**Comment by m-sternak** [comment]
I sued the following commant:
`trcli -y -h <host> --project <project_name> --username <username> --password <password> parse_junit --run-id 43 --case-fields custom_product_id:1 -f "./test-results/junit-report.xml"`

but received an error:

`Found 1 test cases not matching any TestRail case.
Adding missing sections to the suite.
Adding missing test cases to the suite.
Adding test cases: 0/1
Error during add_case. Trying to cancel scheduled tasks.

Aborting: add_case. Trying to cancel scheduled tasks.
Adding test cases: 0/1
Field :custom_product is a required field.
Deleted created section`

**Comment by jakec-routable** [comment]
Based on the error message, looks like you should be using `custom_product` as the field name instead of `custom_product_id` (ex: `--case-fields custom_product:1`. Unless you have both `product` and `product_id` fields, then you would need both.

**Comment by m-sternak** [comment]
it worked. Perfect. Thank you @jakec-routable
