### ISSUE TITLE
Method trcli.data_classes.dataclass_testrail.TestRailResult.__init__() parameter case_id="None" violates type hint <class 'int'>, as <class "builtins.NoneType"> "None"

### ISSUE THREAD

**Issue by meenagokul1005** [gurock/trcli#267]
### TestRail CLI Version

TestRail CLI v1.9.6

### CLI Environment

Python 3.12.5

### TestRail Version

v8.0.4

### TestRail Instance Type

Professional Cloud

### Current behavior

According to the below reference links, I had integrated the trcli with my cypress automation framework. But when Include the trcli code in github actions yml file.

serde.compat.SerdeError: Method trcli.data_classes.dataclass_testrail.TestRailResult.__init__() parameter case_id="None" violates type hint <class 'int'>, as <class "builtins.NoneType"> "None" not instance of int.
Failed to upload test results from cypress/junitReports/merged-test-result.xml

https://support.testrail.com/hc/en-us/articles/7523391639956-Integrating-with-Cypress#01G75119Y2H242KNXNAYXHR3G2

https://support.testrail.com/hc/en-us/articles/7529728971924-Integrating-with-GitHub-Actions#01G74W5ZPGTYQ0PY1K37T54TF0

I was going through the testrail method that was directed in the error 

https://github.com/gurock/trcli/blob/main/trcli/data_classes/dataclass_testrail.py

@serialize
@deserialize
@dataclass
class TestRailCase:
    """Class for creating Test Rail test case"""

    title: str
    section_id: int = field(default=None, skip_if_default=True)
    case_id: int = field(default=None, skip_if_default=True)

### Desired behavior

Testcase creation and Testrun creation in Testrail 

### More Details

here's my cypress.config.js code-

   reporter: 'mocha-junit-reporter',
    reporterOptions: {
      mochaFile: 'cypress/junitReports/results-[hash].xml'
    }

testrail_upload.js

reportFiles.forEach((file) => {
  const command = `trcli -y \
  -h "${testRail.host}" \
     --project "${testRail.project_id}" \
   --username "${testRail.user}" \
   --password "${testRail.api_key}" \
   parse_junit \
   --title "Cypress Automated Test Run" \
   -f "${file}" \
   --suite-id "${testRail.suite_id}" \
  --case-fields custom_automation_type:1 \
  --case-fields case_id:0` ;

  try {
    execSync(command, { stdio: 'inherit' });
    console.log(`Test results from ${file} uploaded successfully.`);
  } catch (error) {
    console.error(`Failed to upload test results from ${file}:`, error);
    process.exit(1);
  }
});

GithubActions - yml file 

     - name: Merge junit files
        run: junitparser merge --glob "cypress/junitReports/results-*" "cypress/junitReports/merged-test-result.xml"

     - name: Upload JUnit test reports
        uses: actions/upload-artifact@v3
        with:
          name: junit-reports
          path: cypress/junitReports/merged-test-result.xml # Path to the JUnit reports

     - name: Execute TestRail CLI to upload results
        if: always()
        run: |  
          pip install trcli
          trcli
          node testrail_upload.js

merged-test-result.xml file

<testsuites tests="2" failures="1" errors="0" skipped="0" time="0.223"><testsuite name="Root Suite" timestamp="2024-09-02T08:33:10" tests="0" file="cypress/e2e/Audits.feature" time="0" failures="0" errors="0" skipped="0">
  </testsuite>
  <testsuite name="Audit Page" timestamp="2024-09-02T08:33:10" tests="1" time="0.109" failures="1" errors="0" skipped="0">
    <testcase name="Audit Page Verify Audit with Valid Credentials" time="0.109" classname="Verify Audit with Valid Credentials">
       <failure message="expected false to equal undefined" type="AssertionError"><![CDATA[AssertionError: expected false to equal undefined
    at Context.eval (node_modules/@badeball/cypress-cucumber-preprocessor/dist/browser-runtime.js:490:0)]]></failure>
    </testcase>
  </testsuite>
<testsuite name="Root Suite" timestamp="2024-09-02T08:33:14" tests="0" file="cypress/e2e/Login.feature" time="0" failures="0" errors="0" skipped="0">
  </testsuite>
  <testsuite name="Login Page" timestamp="2024-09-02T08:33:14" tests="1" time="0.114" failures="0" errors="0" skipped="0">
    <testcase name="Login Page Verify Login with Valid Credentials" time="0.114" classname="Verify Login with Valid Credentials">
    </testcase>
  </testsuite>
</testsuites>

**Comment by acuanico-tr-galt** [comment]
Hello! Thank you for raising this issue. We have published a fix for the issue above. This relates to the pyserde dependency strict type enforcement. Kindly check the latest release v1.9.7. We appreciate your support and understanding.

**Comment by meenagokul1005** [comment]
Thank you its fixed now
