### ISSUE TITLE
TRCLI v1.9.6 breaks while uploading Cypress results to testrail

### ISSUE THREAD

**Issue by gjambaisivanandham** [gurock/trcli#270]
### TestRail CLI Version

v1.9.6

### TestRail Version

8.0.4 Default (7036)

### TestRail Instance Type

Professional Cloud

### Current behavior

We are running Cypress tests in parallel in CircleCI and have custom CI script to consolidate test results from all the parallel test runs and then we make a call to testrail using trcli to update test results in Testrail. This was working as expected in trcli v1.9.5 but it broke with the latest trcli v1.9.6 release. Here is an example of the consolidated xml file, just in case if this is useful for any of your troubleshooting purposes. 

```<?xml version='1.0' encoding='utf-8'?> <testsuites><testsuite name="merged-testsuite"><testcase name="Tests for auth" file="cypress/tests/auth.cy.js" time="1.5200" classname="validate auth section" /> <testcase name="login" file="cypress/tests/login.cy.js" time="1.3350" classname="login to account" /> <testcase name="logout" file="cypress/tests/logout.cy.js" time="1.5860" classname="logout from account" /> </testsuite></testsuites>``` 

Here is the error message thrown by trcli v1.9.6 .

```> Project: Cypress Integration Tests > Run title: Automated Cypress Tests from CircleCI workflow > Update run: No > Add to milestone: No > Auto-create entities: True Parsing JUnit report. Traceback (most recent call last): File "/home/circleci/.pyenv/versions/3.11.9/bin/trcli", line 8, in <module> sys.exit(cli()) ^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__ return self.main(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/trcli/cli.py", line 242, in main return super().main(windows_expand_args=False, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main rv = self.invoke(ctx) ^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke return ctx.invoke(self.callback, **ctx.params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/trcli/commands/results_parser_helpers.py", line 101, in wrapper_common_options return f(*args, **kwargs) ^^^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func return f(get_current_context(), *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func return ctx.invoke(f, obj, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke return __callback(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/trcli/commands/cmd_parse_junit.py", line 34, in cli parsed_suites = JunitParser(environment).parse_file() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/circleci/.pyenv/versions/3.11.9/lib/python3.11/site-packages/trcli/readers/junit_xml.py", line 155, in parse_file result = TestRailResult( ^^^^^^^^^^^^^^^ File "<@beartype(trcli.data_classes.dataclass_testrail.TestRailResult.__init__) at 0x7f205be3d940>", line 35, in __init__ serde.compat.SerdeError: Method trcli.data_classes.dataclass_testrail.TestRailResult.__init__() parameter case_id="None" violates type hint <class 'int'>, as <class "builtins.NoneType"> "None" not instance of int. Exited with code exit status 1 ``` 

Could you please help fix this on priority since this broke an existing flow.

### Desired behavior

TRCLI v 1.9.6 shouldn't break the existing functionality in v 1.9.5

**Comment by jakec-routable** [comment]
This is already fixed in v1.9.7

**Comment by gjambaisivanandham** [comment]
> This is already fixed in v1.9.7

Thanks for the update, I'll check in the latest version.

**Comment by gjambaisivanandham** [comment]
No longer an issue in v1.9.7. Thank you @jakec-routable!
