### ISSUE TITLE
CLI does not match automation_id with test cases's classname and name

### ISSUE THREAD

**Issue by mecciau** [gurock/trcli#70]
Hello 👋 

We're trying to match automation_id with case's classname and name, but it seems to not work correctly. Steps we taken trying to achieve this:

- Created a new [custom field](https://www.gurock.com/testrail/docs/user-guide/howto/fields/) of type `String` with system name `automation_id`.
- Our test framework (Playwright) generated a Junit report xml file
- We added an automation_id field in one of the cases we have described. It matches the pattern which get created from `<testcase>` classname and name, for example `hello.world`
- We use the CLI to upload the file `trcli -c testrail.config.yml parse_junit`
```
Checking project. Done.
Adding missing sections to the suite.
Creating test run. Done.
Adding results: 0/0, Done.
Done.
```
Got:
it creates a new section with a name taken from `<testsuite>` name (in our case filename) and the section is empty. The test case, where the test result should be posted is empty as well. 

Expected:
To post automated test results to test case with id `hello.world`

**Comment by d-rede** [comment]
Hi @mecciau 🙂

Thanks for reaching out! Seems like no tests are being parsed from your report. Do you think you could provide a sample of the xml file? One or two test cases would be enough in order to investigate the issue.

Cheers,
Diogo

**Comment by mecciau** [comment]
Hi @d-rede,

please find a sample xml attached. 2 passed, 1 failed test.


```
<testsuites id="" name="" tests="3" failures="1" skipped="0" errors="0" time="2.172">
<testsuite name="my_test.spec.ts" timestamp="1653394826947" hostname="" tests="3" failures="1" skipped="0" time="1.805" errors="0">
<testcase name="world" classname="hello" time="1.531">
</testcase>
<testcase name="world2" classname="hello2" time="0.056">
<failure message="my_test.spec.ts:8:1 fail" type="FAILURE">
  [chrome] › my_test.spec.ts:8:1 › fail ===========================================================

    Error: expect(received).toBeTruthy()

    Received: false

       7 |
       8 | test("fail", async ({ page }) => {
    >  9 |   expect(false).toBeTruthy();
         |                 ^
      10 | });
      11 |
      12 | test("success", async ({ page }) => {

        at /Users/dv/pw/tests/my_test.spec.ts

</failure>
</testcase>
<testcase name="world3" classname="hello3" time="0.218">
</testcase>
</testsuite>
</testsuites>
```

**Comment by d-rede** [comment]
@mecciau unfortunately I'm not able to replicate the issue. Everything seems to be working as expected using the command below with the report you provided.

Can you share the following details for further debugging?
- Command you are using
- Python version
- TestRail account type (professional/enterprise and server/cloud)
- TestRail version

```
trcli -y -h "https://INSTANCE.testrail.io" --project "TRCLI Tests" -u "USERNAME" -p "PASSWORD" parse_junit --title "Playwright Automated Test Run" -f "playwright_issue.xml"
```
```
Checking project. Done.
Adding missing sections to the suite.
Found test cases not matching any TestRail case (count: 3)
Adding missing test cases to the suite.
Adding test cases: 3/3, Done.
Creating test run. Done.
Adding results: 3/3, Done.
Done.
Submitted 3 test results in 6.8 secs.
```

**Comment by mecciau** [comment]
hey @d-rede ,

from your cli output it seems like **you did not have the custom field set up**. 

however, here are my details you requested:

Command you are using (with config details)
`trcli -c testrail.config.yml parse_junit`
testrail.config.yml:
```
host: https://x.testrail.io/
project: x
username: x
password: x
file: ../results.xml
title: Testing playwright integration 7
auto_creation_response: true
suite_id: 32
```

Python version
`python 3.9`

TestRail account type (professional/enterprise and server/cloud)
`Professional Cloud`

TestRail version
not sure what do you mean by that

**Comment by d-rede** [comment]
Hi @mecciau and sorry for the late reply!

What do you mean by **you did not have the custom field set up**? I noticed you mentioned on the issue that you _Created a new [custom field](https://www.gurock.com/testrail/docs/user-guide/howto/fields/) of type String with system name automation_id._ as per the installation instructions, is this not right?

Have you been able to make any further progress? I can't really help without more info.

**Comment by JeffHall** [comment]
I'm experiencing the same issue as @mecciau.  

Using the verbose mode for the trcli tool, I can verify (via the results of the "get_cases" request) that I have a test case with a certain automation_id value:

`'custom_automation_id': 'graphql.test_authentication.test_get_auth_token'`

The Junit XML file that I am using as input seems to follow the correct convention to match that automation_id value:

`<?xml version="1.0" encoding="utf-8"?>
<testsuites name="Master">
	<testsuite name="external_api" errors="0" failures="0" skipped="0" tests="1" time="0.528" timestamp="2022-06-29T15:35:59.652034" hostname="<value>">
		<testcase classname="graphql.test_authentication" name="test_get_auth_token" time="0.482"/>
	</testsuite>
</testsuites>`

...but when I run the trcli tool like so:

`trcli -y -h "<value>" --project "TestRail CLI evaluation" --project-id 19 -u "<value>" -p "<value>" --verify --insecure --verbose parse_junit --title "Sandbox test run" -f "test_results.xml"`

...a new test run is created in TestRail, but the existing test case does not get added to that test run.

**Comment by mecciau** [comment]
@d-rede please find a video attached showing the issue

https://user-images.githubusercontent.com/17064417/177128185-f6c66504-ff98-40a5-ac20-13add687e9b3.mp4

**Comment by tdnguyen84** [comment]
Hi @d-rede , I guess my issue maybe the same with someone here or I may not understand the function of Testrail CLI correctly, feel free to correct me. My issue is:
1. Let's say I set up automation_id custom field for my project
2. My junit xml like below
```xml
<testsuites name="test suites root">
  <testsuite failures="0" errors="0" skipped="1" tests="1" time="0.05" name="LoginTests">
    <properties><property name="setting1" value="True"/></properties>
    <testcase classname="LoginTests" name="test_case_1" time="159">
      <skipped type="pytest.skip" message="Please skip">skipped by user</skipped>
    </testcase>
    <testcase classname="LoginTests" name="test_case_2" time="650">
    </testcase>
  </testsuite>
</testsuites>
```

3. In TesRail, my project will have section & test cases are structured as below

```
LoginTests
|
|____Test case 1 (has Automation ID = `LoginTests.test_case_1`)
|
|____Test case 2 (has Automation ID = `LoginTests.test_case_2`)
```

4. Now when I run the Testrail CLI with right configure and I'm seeing
   - It can create a new Test Run, but there neither test case "Test case 1" nor "Test case 2" are added to the test run

**My expectation:**
- It should it should add the existing test cases "Test case 1" and "Test case 2" to the test run because they have the "Automation ID" matched with combination "classname.name" of <testcase> node in xml file

**What I played around**
- If I rename my test cases in TestRail like "test_case_1" and "test_case_2" with the Automation ID are still like above
- Re-run TestRail CLI, those existing test cases will be added to test run successfully

**So my concern and question**
Are we requiring both test case name and automation id  in TestRail to be able to map the existing test cases to add to test run when running TestRail CLI?

My use case here is, I have a lot of test cases defined in TestRail that were set the names are not the same in automation test scripts. So we just tried to update the Automation IDs with the format we defined in TestRail CLI document and hopefully the tool can base on the automation ids to add to test result.

**Comment by d-rede** [comment]
Hey @mecciau 
Before anything, sorry for leaving this hanging for so long. I created a fix related to test case name/title, which should be totally disregarded when matching cases. Can you test if that also solves your issue? You just need to update trcli to version 1.3.1
