### ISSUE TITLE
Support importing of required fields

### ISSUE THREAD

**Issue by Testinator-X** [gurock/trcli#73]
**Steps to reproduce**
* Create a mandatory custom Field, e.g. a List of "custom_affected_companies" and apply it to a TestCase for the project you wish to import your TestCases to. 
* Set the results.version Field to mandatory 
* Import Testcases

**Actual Result**
* error occured while creating a TestCase via import: `Field :results.version is a required field`. 
* error occured while adding a result via import: `Field :custom_affected_companies is a required field.` 
* I had to edit the result field and set “required” to false to be able to import.
* I had to edit the field and set “required” to false to be able to import. 

**Expected Result**
* it should be possible to provide mandatory informations, per TestCase
* it should be possible to provide mandatory informations, per Result

**Comment by d-rede** [comment]
Hello @Testinator-X 

Thanks for this great suggestion! Seems like a common problem affecting more users.
The case fields argument is now available on [TR CLI v1.1.0](https://github.com/gurock/trcli/releases/tag/v1.1.0). As for the result fields, we're still in the process of evaluating the implementation.

Command line usage:
```sh
--case-fields type_id:1 --case-fields priority_id:3
```
Config file usage:
```yaml
case_fields: 
  type_id: 1,
  priority_id: 3
```

Let me know how that works for you!

**Comment by Testinator-X** [comment]
@d-rede now I get the following error when I try to import "Field :custom_affected_companies is not a valid array."

I tried to provide the IDs of my custom multiselect field in the following ways:

1. --case-fields custom_affected_companies:0
2. --case-fields custom_affected_companies:0,1
3. --case-fields custom_affected_companies:{0,1}
4. --case-fields custom_affected_companies:[0,1]
5. --case-fields custom_affected_companies:0;1
6. --case-fields custom_affected_companies:[0;1]
7. --case-fields custom_affected_companies:{0;1}

How to provide an array of IDs?

**Comment by deepashree-dexcom** [comment]
Hi , I am also running into the exact same issue . Any help is appreciated

**Comment by Testinator-X** [comment]
@d-rede help!

**Comment by d-rede** [comment]
Hello @Testinator-X 

Sorry I missed this query. Submitting lists of values is not currently supported through the command line, but you can use the configuration files to do so, using one of the following notations:
```
case_fields: 
  custom_affected_companies: [0, 1]

OR

case_fields: 
  custom_affected_companies:
    - 0
    - 1
```

Let me know if this helps.

**Comment by d-rede** [comment]
@Testinator-X this is now supported in `trcli v1.4.1`
