### ISSUE TITLE
api version not checked for get_projects

### ISSUE THREAD

**Issue by fwagers** [gurock/trcli#76]
In my organization's api response for the get_projects, we do not receive a "projects" field to summarize all projects. It is simply a list of projects. This causes an exception for the list comprehension on line 73 in api_request_handler.py. Is this library only compatible for a specific version? 

```
            available_projects = [
                project
                for project in response.response_text["projects"] <--- this field doesn't exist for us
                if project["name"] == project_name
            ]
```

**Comment by d-rede** [comment]
Hi @fwagers 

Sorry to hear you are having trouble. It does sound like an API incompatibility issue. Do you mind sharing your organization's TestRail version so I can look into it? Thanks!

**Comment by shivangipathak01** [comment]
Hey 
I wanted to know if there have been any updates or fixes for this issue?
My organization is using Testrail version v7.0.1.1013 and I get the same error of your code not being able to find the "projects" key in the response

**Comment by d-rede** [comment]
Hey everyone!

Just letting you know the legacy endpoints are now supported on https://github.com/gurock/trcli/releases/tag/v1.2.0 

Let me know if you still run into trouble!
