### ISSUE TITLE
Enhance click.options for host, username, and password leverage envvars. Then add support for .env file.

### ISSUE THREAD

**Issue by fwagers** [gurock/trcli#78]
It's cli hell to have to pass all these values in. Yes, there is a configuration file option but that's too broad.

Please pick a standard for the environment variables, I suggest TESTRAIL_USR, TESTRAIL_PSW, and TESTRAIL_HOST, so that we can have these set automatically without having to pass them in. In addition, have a .env file click option so that we can test these variables without having to set them in our bash profile or explicitly. 

Finally, configuration files should be broken into categories. 

Config file 1 (new run):
suite_id <- required
milestone_id <- optional if you want that run placed in a milestone
plan_id <- optional if you want that run placed in plan

Config file 2 (existing run):
run_id

**Comment by d-rede** [comment]
Hi @fwagers 

Thanks for the suggestions, let's go piece by piece.

#### Environment variables
Using environment variables is already supported by using the pattern `TR_CLI_PARAMETER_NAME_CAPITALIZED`. Please take a look at the [Environment Variables section](https://github.com/gurock/trcli/tree/v1.1.0#environment-variables) on the README file.

#### .env file
This is something we could look at, but sounds to me like it would have the same effect as the config files, correct me if I'm wrong.

#### Config files broken into categories
You can have multiple config files and pass them to the CLI according to your necessity, i.e.:
```sh
# New run
trcli -c new_run_config.yml parse_junit report.xml
# Existing run
trcli -c existing_run.yml parse_junit report.xml
```


Also, you can combine multiple types of parameters, just be aware of the priorities as per the table on the [Setting parameters from different places](https://github.com/gurock/trcli/tree/v1.1.0#setting-parameters-from-different-places) section on the README file.

Let me know if any of this works for you or if I missed the point.

**Comment by d-rede** [comment]
Closing due to no further info. Please feel free to bring this up again if it still makes sense.
